In [1]:
import pandas as pd

df = pd.read_csv("HR_Analytics.csv")

In [2]:
total_emp = len(df)
attrition_count = df[df['Attrition'] == 'Yes'].shape[0]

attrition_rate = (attrition_count / total_emp) * 100

print(attrition_rate)

16.08108108108108

In [3]:
df.groupby('Department')['Attrition'].value_counts().unstack()

Attrition                No  Yes
Department
Human Resources          51   12
Research & Development  834  133
Sales                   357   93

In [4]:
df[df['Attrition'] == 'Yes']['MonthlyIncome'].mean()

np.float64(4812.584033613445)

In [5]:
pd.crosstab(df['OverTime'], df['Attrition'])

Attrition   No  Yes
OverTime
No         952  110
Yes        290  128

In [6]:
df.groupby('JobRole')['Attrition'].value_counts().unstack()

Attrition                   No  Yes
JobRole
Healthcare Representative  123    9
Human Resources             40   12
Laboratory Technician      199   62
Manager                     97    5
Manufacturing Director     137   10
Research Director           78    2
Research Scientist         246   47
Sales Executive            271   58
Sales Representative        51   33

In [7]:
df.groupby('WorkLifeBalance')['Attrition'].value_counts().unstack()

Attrition         No  Yes
WorkLifeBalance
1                 56   25
2                288   58
3                771  128
4                127   27

In [8]:
df.groupby('AgeGroup')['Attrition'].value_counts().unstack()

Attrition   No  Yes
AgeGroup
18-25       79   44
26-35      495  116
36-45      428   43
46-55      201   27
55+         39    8

In [9]:
df.groupby('YearsAtCompany')['Attrition'].value_counts().unstack()

Attrition          No   Yes
YearsAtCompany
0                28.0  16.0
1               112.0  59.0
2               100.0  27.0
3               108.0  21.0
4                93.0  19.0
5               177.0  21.0
6                68.0   9.0
7                80.0  11.0
8                71.0   9.0
9                76.0   8.0
10              102.0  18.0
11               30.0   2.0
12               14.0   NaN
13               22.0   2.0
14               16.0   2.0
15               19.0   1.0
16               11.0   1.0
17                8.0   1.0
18               12.0   1.0
19               10.0   1.0
20               27.0   1.0
21               13.0   1.0
22               14.0   1.0
23                1.0   1.0
24                5.0   1.0
25                4.0   NaN
26                4.0   NaN
27                2.0   NaN
29                2.0   NaN
30                1.0   NaN
31                2.0   1.0
32                2.0   1.0
33                4.0   1.0
34                1.0   NaN
36                2.0   NaN
37                1.0   NaN
40                NaN   1.0